### ISSUE TITLE
Backup of grub config fails on Rocky8

### ISSUE THREAD

**Issue by gc-nathanh** [stackhpc/ansible-role-grubcmdline#9]
TASK [stackhpc.grubcmdline : replace current grub config] step fails on Rocky8, but only has an issue with 'backup'.   Commenting out 'backup: true' allows the playbook to continue. 

`failed: [gbnwp-pod049-3] (item=/etc/grub2-efi.cfg) => {"ansible_loop_var": "item", "changed": false, "checksum": "009acbac7ec674e120305a598eb373a92e29b20a", "item": "/etc/grub2-efi.cfg", "msg": "Could not make backup of /boot/efi/EFI/rocky/grub.cfg to /boot/efi/EFI/rocky/grub.cfg.15059.2022-10-19@10:11:59~: [Errno 22] Invalid argument: '/boot/efi/EFI/rocky/grub.cfg.15059.2022-10-19@10:11:59~'"}`

**Comment by Alex-Welsh** [comment]
Seems like this is related to some filesystems not liking the characters in the filename e.g. `:`
An option to skip the backup has been added here: https://github.com/stackhpc/ansible-role-grubcmdline/pull/10
